FROM debian:stable-slim

# set a directory for the app
WORKDIR /root

# procps for ps
RUN apt-get update && apt-get install -y tcsh \
                                        gawk \
                                        vim \
                                        procps \
                                        wget \
                                        imagemagick \
                                        gnuplot

# copy all the necessary files to the container
COPY .netrc ./src ./

RUN ln -s /root/run/sta_pos.tot /root/dat/sta_pos.tot

ENTRYPOINT ["/bin/tcsh"]